Miscellaneous minor changes
mappingtools/Mapperator pull request #2
Opened 2022-10-15 21:42 UTC by khang06

These are just some local changes that I cleaned up because they might be useful. Look at the individual commits for more details.

2022-10-15 23:53 UTC, OliBomby requested changes

2022-10-15 23:53 UTC, OliBomby commented on Mapperator/Construction/BeatmapConstructor.cs
> +                            if (Vector2.DistanceSquared(ogPos, pos) > Precision.DOUBLE_EPSILON) {
this NaN check should remain i think

2022-10-15 23:59 UTC, khang06 commented on Mapperator/Construction/BeatmapConstructor.cs
> +                            if (Vector2.DistanceSquared(ogPos, pos) > Precision.DOUBLE_EPSILON) {
oops, i forgot there was another position comparison. would it make more sense to do `Vector2.DistanceSquared(ogPos, pos) > Precision.DOUBLE_EPSILON && Vector2.DistanceSquared(ogPos, lastSlider.EndPos) > Precision.DOUBLE_EPSILON`?

2022-10-16 08:28 UTC, OliBomby approved these changes

2022-10-16 08:28 UTC, merged